# Spécifie la racine des documents du site
root /app;

# Ajoute index.php à la liste des fichiers d'index
index index.html index.htm index.php;

location / {
    try_files $uri $uri/ =404;
}

# Configuration pour le passage des scripts PHP à PHP-FPM
# Décommenter et remplacer les lignes 30 à 36
location ~ \.php$ {
    # Racine des documents
    root /app;
    
    # Le nom 'script' est le nom du service (container PHP-FPM) sur notre réseau Docker
    fastcgi_pass script:9000;
    
    fastcgi_index index.php;
    
    # Définit le chemin du script PHP à exécuter
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    
    # Inclut les paramètres FastCGI standards
    include fastcgi_params;
}
